// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/home": {
    params: {};
  };
  "/library": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/*" | "/home" | "/library";
  };
  "catchall.jsx": {
    id: "catchall";
    page: "/" | "/*";
  };
  "./components/WelcomePage/WelcomePage.jsx": {
    id: "components/WelcomePage/WelcomePage";
    page: "/";
  };
  "./components/Home/Home.jsx": {
    id: "components/Home/Home";
    page: "/home";
  };
  "./components/Library/Library.jsx": {
    id: "components/Library/Library";
    page: "/library";
  };
};